const services=[['Consultas clínicas','Un espacio para revisar su salud, conversar sobre sus hábitos y acompañarte con un plan de cuidado para cada etapa.','0% 0%'],['Vacunación','Revisamos su carnet y coordinamos las vacunas indicadas según su edad, antecedentes y necesidades.','50% 0%'],['Desparasitación','Cuidado frente a parásitos internos y externos, con orientación para elegir la prevención adecuada para tu mascota.','100% 0%'],['Cirugías','Evaluación previa, orientación sobre el procedimiento y acompañamiento en los cuidados de recuperación.','0% 100%'],['Análisis de laboratorio','Estudios que aportan información para evaluar su salud, orientar el diagnóstico y realizar controles.','50% 100%'],['Ecografía','Estudios por imágenes para observar órganos internos y complementar la evaluación veterinaria.','100% 100%'],['Cardiología','Evaluación de la salud del corazón y orientación sobre los estudios y controles que puede necesitar.','0% 0%']];
const schedule=[['Lunes','16:00 a 19:00'],['Martes','09:00 a 13:00 · 16:00 a 19:00'],['Miércoles','16:00 a 19:00'],['Jueves','09:00 a 13:00 · 16:00 a 19:00'],['Viernes','09:00 a 13:00 · 16:00 a 20:00'],['Sábado','09:00 a 13:00 · 16:00 a 20:00'],['Domingo','10:00 a 13:00']];
const grid=document.querySelector('#service-grid');if(grid)grid.innerHTML=services.map(([name,desc,pos],i)=>`<a class="service-card reveal" href="contacto.html?servicio=${encodeURIComponent(name)}"><div class="service-photo"><div role="img" aria-label="Imagen ilustrativa de ${name.toLowerCase()} veterinaria" style="background-position:${pos}"></div></div><div class="service-body"><span class="service-number">CUIDADO / 0${i+1}</span><div class="service-title"><h3>${name}</h3><span aria-hidden="true">↗</span></div><p>${desc}</p><span class="service-cta">Consultar por este servicio <b aria-hidden="true">↗</b></span></div></a>`).join('');
document.querySelectorAll('.hours-list').forEach(el=>el.innerHTML=schedule.map(([d,h])=>`<div><dt>${d}</dt><dd>${h}</dd></div>`).join(''));
document.querySelectorAll('.whatsapp').forEach(el=>el.innerHTML='<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7" aria-hidden="true"><path d="M20.4 11.7a8.4 8.4 0 0 1-12.5 7.4L3 20.5l1.4-4.7a8.4 8.4 0 1 1 16-4.1Z"/><path d="M8 7c-2 2 2 8 6 9 1 .2 3-1.5 2-2l-2-1-1 1c-2-.8-3-2-3.5-3.5l1-1L9.5 7Z"/></svg>');
if(!matchMedia('(prefers-reduced-motion: reduce)').matches){document.documentElement.classList.add('js-motion');const observer=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){e.target.classList.add('visible');}else{e.target.classList.remove('visible')}}),{threshold:.08});document.querySelectorAll('.reveal').forEach((e,i)=>{e.dataset.side=i%2?'right':'left';observer.observe(e)});const bg=document.querySelector('.parallax-image');if(bg){let scheduled=false;const update=()=>{const rect=bg.parentElement.getBoundingClientRect();if(rect.bottom>0&&rect.top<innerHeight)bg.style.transform=`translateY(${(innerHeight/2-rect.top-rect.height/2)*.16}px)`;scheduled=false};addEventListener('scroll',()=>{if(!scheduled){scheduled=true;requestAnimationFrame(update)}},{passive:true});update()}}
const form=document.querySelector('#contact-form');if(form){const select=form.elements.servicio;services.forEach(([name])=>select.add(new Option(name,name)));select.add(new Option('Otra consulta','Otra consulta'));const requested=new URLSearchParams(location.search).get('servicio');if(services.some(s=>s[0]===requested))select.value=requested;const date=form.elements.fecha;const now=new Date();date.min=`${now.getFullYear()}-${String(now.getMonth()+1).padStart(2,'0')}-${String(now.getDate()).padStart(2,'0')}`;const windows={0:[[10,13]],1:[[16,19]],2:[[9,13],[16,19]],3:[[16,19]],4:[[9,13],[16,19]],5:[[9,13],[16,20]],6:[[9,13],[16,20]]};date.addEventListener('change',()=>{const day=new Date(date.value+'T12:00:00').getDay();const hour=form.elements.horario;hour.innerHTML='<option value="">Elegí un horario</option>';(windows[day]||[]).forEach(([start,end])=>{for(let h=start;h<end;h++)for(const m of ['00','30'])hour.add(new Option(`${String(h).padStart(2,'0')}:${m}`,`${String(h).padStart(2,'0')}:${m}`))})});form.addEventListener('submit',e=>{e.preventDefault();if(!form.reportValidity())return;const data=new FormData(form);const msg=`Hola, Veterinaria Tradición. Quisiera coordinar una atención.\n\nNombre: ${data.get('nombre')}\nTeléfono: ${data.get('telefono')}\nEmail: ${data.get('email')||'No indicado'}\nMascota: ${data.get('mascota')}\nEspecie: ${data.get('especie')}\nEdad: ${data.get('edad')||'No indicada'}\nServicio: ${data.get('servicio')}\nFecha preferida: ${data.get('fecha')}\nHorario preferido: ${data.get('horario')}\nConsulta: ${data.get('mensaje')}\n\nEntiendo que el turno queda sujeto a confirmación.`;const url='https://wa.me/5491135204743?text='+encodeURIComponent(msg);window.open(url,'_blank','noopener,noreferrer');const status=document.querySelector('#form-status');status.replaceChildren(document.createTextNode('Tu consulta está preparada. Completá el envío en WhatsApp. Si no se abrió, '));const link=document.createElement('a');link.href=url;link.target='_blank';link.rel='noopener noreferrer';link.textContent='abrilo desde acá ↗';status.append(link)})}
// Independent pet layer: pointer perspective and scroll depth.
const heroScene=document.querySelector('.hero');
if(heroScene&&!matchMedia('(prefers-reduced-motion: reduce)').matches){
 let frame=0,pointerX=0,pointerY=0;
 const renderDepth=()=>{frame=0;const rect=heroScene.getBoundingClientRect();if(rect.bottom<0)return;const layer=heroScene.querySelector('.hero-pets');layer.style.setProperty('--pet-x',`${pointerX*14}px`);layer.style.setProperty('--pet-y',`${pointerY*9+Math.min(100,Math.max(0,-rect.top)*.13)}px`);layer.style.setProperty('--pet-rotate',`${pointerX*3}deg`)};
 const queueDepth=()=>{if(!frame)frame=requestAnimationFrame(renderDepth)};
 heroScene.addEventListener('pointermove',e=>{if(e.pointerType==='touch')return;const r=heroScene.getBoundingClientRect();pointerX=(e.clientX-r.left)/r.width-.5;pointerY=(e.clientY-r.top)/r.height-.5;queueDepth()});
 heroScene.addEventListener('pointerleave',()=>{pointerX=0;pointerY=0;queueDepth()});addEventListener('scroll',queueDepth,{passive:true});
}
